export const SITE = {
  name: "LyliShop",
  domain: "lylishop.online",
  url: "https://lylishop.online",
  locale: "vi_VN",
  title: "Móc Khóa Len Handmade Cute | LyliShop",
  brandDescription:
    "Shop móc khóa len handmade cute, nhận làm móc khóa len theo yêu cầu, phù hợp làm quà tặng dễ thương cho học sinh, sinh viên và người yêu thích đồ handmade.",
  description:
    "Móc khóa len handmade cute từ LyliShop: phụ kiện len nhỏ xinh, đóng gói làm quà, nhận chọn màu theo yêu cầu và đặt nhanh qua Zalo/Facebook.",
  keywords: [
    "móc khóa len",
    "móc khoá len",
    "móc khóa len handmade",
    "móc khoá len handmade",
    "móc khóa handmade",
    "móc khóa crochet",
    "móc khóa thú len",
    "móc khóa dễ thương",
    "quà tặng handmade",
    "quà tặng nhỏ xinh",
    "thú len handmade",
    "quà tặng crochet",
    "phụ kiện len handmade",
    "móc treo len",
    "móc khóa thỏ handmade",
  ],
  themeColor: "#be185d",
  ogImage: "/og.png",
  twitterImage: "/twitter-card.png",
  logo: "/apple-touch-icon-lylishop-v3.png",
  phone: "0356839196",
  google: {
    analyticsMeasurementId: "G-MJ7EP9BPQH",
    adsId: "AW-18205425232",
    searchConsoleVerification: "CJ6HkBRGaUnGabnWhbRFvP3EDaClZkRuQvZQBSuwAGE",
  },
  socials: {
    instagram: "https://www.instagram.com/lylishopstr/",
    tiktok: "https://www.tiktok.com/@lylistr1105",
    facebook: "https://www.facebook.com/profile.php?id=61579372469264",
    zalo: "https://zalo.me/0356839196",
  },
} as const;
