export const SITE = {
  name: "LyliShop",
  domain: "lylishop.online",
  url: "https://lylishop.online",
  locale: "vi_VN",
  title: "LyliShop | Móc khóa len handmade & phụ kiện len",
  description:
    "Khám phá móc khóa len handmade và phụ kiện len nhỏ xinh từ LyliShop. Len mềm cao cấp, đóng gói quà chỉn chu, có thể tùy chỉnh màu và đặt hàng qua tin nhắn.",
  keywords: [
    "móc khóa len",
    "móc khoá len",
    "móc khóa len handmade",
    "móc khoá len handmade",
    "móc khóa handmade",
    "móc khóa crochet",
    "móc khóa thú len",
    "móc khóa dễ thương",
    "quà tặng handmade",
    "quà tặng nhỏ xinh",
    "thú len handmade",
    "quà tặng crochet",
    "phụ kiện len handmade",
    "móc treo len",
    "móc khóa thỏ handmade",
  ],
  themeColor: "#be185d",
  ogImage: "/og.png",
  twitterImage: "/twitter-card.png",
  logo: "/logo-lylishop-v3.svg",
  google: {
    analyticsMeasurementId: "G-MJ7EP9BPQH",
    adsId: "AW-18205425232",
    searchConsoleVerification: "CJ6HkBRGaUnGabnWhbRFvP3EDaClZkRuQvZQBSuwAGE",
  },
  socials: {
    instagram: "https://www.instagram.com/lylishopstr/",
    tiktok: "https://www.tiktok.com/@lylistr1105",
    facebook: "https://www.facebook.com/profile.php?id=61579372469264",
    zalo: "https://zalo.me/0356839196",
  },
} as const;
